### ISSUE TITLE
Helm charts/podinfo/templates/ingress.yaml can't evaluate field hosts

### ISSUE THREAD

**Issue by qLb** [stefanprodan/podinfo#147]
I'm trying to test my cluster with podinfo chart created with fluxcd but it seems it breaks on `values.ingress.hosts`.
```
Helm upgrade failed: template: podinfo/templates/ingress.yaml:20:18: executing "podinfo/templates/ingress.yaml" at <.hosts>: can't evaluate field hosts in type interface {} Last Helm logs: preparing upgrade for podinfo resetting values to the chart's original version
```

And here's my helmrelease:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: staging
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
      version: ">=1.0.0-alpha"
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    cache: redis-master.redis:6379
    ingress:
      className: "traefik"
      enabled: true
      hosts:
        - host: stage.mydomain.com
          paths:
          - path: /
            pathType: ImplementationSpecific
      tls:
        secretName: panel-secret
        domains:
          - main: stage.mydomain.com
```

@stefanprodan i'd appreciate any help ;)
