### ISSUE TITLE
Use service account in tests

### ISSUE THREAD

**Issue by Boojapho** [stefanprodan/podinfo#150]
I'd like to be able to run the Helm tests using a private repo to demonstrate how this is done.  The service account can be added to the tests that pull images by adding this to the Pod specs:

```yaml
spec:
  {{- if .Values.serviceAccount.enabled }}
  serviceAccountName: {{ template "podinfo.serviceAccountName" . }}
  {{- end }}
```
