### ISSUE TITLE
aad-pod-identity demo?

### ISSUE THREAD

**Issue by jobinjosem** [stefanprodan/podinfo#287]
Can I use the podinfo image for aad-pod-identity demo? Will it work as expected if I add the details of identity to the manifests?

**Comment by ljluestc** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfo
          image: stefanprodan/podinfo
          ports:
            - containerPort: 9898
          env:
            - name: AZURE_AUTHORITY_HOST
              value: "https://login.microsoftonline.com"
            - name: AZURE_TENANT_ID
              value: "<your-tenant-id>"
            - name: AZURE_CLIENT_ID
              value: "<your-client-id>"
            - name: AZURE_RESOURCE_ID
              value: "<your-resource-id>"
          # ...
        # ...
```
