### ISSUE TITLE
Can't get podinfo to work with MetalLB

### ISSUE THREAD

**Issue by bozho** [stefanprodan/podinfo#379]
Hi, this is most likely due to my noobiness, but I can't get `podinfo` to work with `metallb`.

I have a simple cluster, 3 control plane nodes, 2 worker nodes (local network, no firewalls), `cilium` as the network layer and using `flux` for CD. `metallb` is is set up with a 3-address IP pool and L2 advertisement.

I deploy a generic `nginx` deployment with a `LoadBalancer` service:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu:    "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
```
That works fine. `nginx` service is deployed with no errors, its external IP is one from the IP pool range, and I can do `curl <external IP>` from  my machine.

However, when I deploy `podinfo` service (using the "Get Started" `flux` doc), with its service patched to `LoadBalancer` type:
```
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: podinfo
    spec:
      ports:
        - name: http
          port: 9898
          protocol: TCP
          targetPort: 8080
        - name: grpc
          port: 9999
          protocol: TCP
          targetPort: 8081
      selector:
        app: podinfo
      type: LoadBalancer
```
I see `podinfo` service type switch to `LoadBalancer`, its external IP is another IP from the pool range, but `curl <podinfo external IP>:8080` from my machine times out. If I deploy `podinfo` with defaults from the tutorial, I can do `curl <podinfo cluster IP>:9898` on a cluster node.

Where do I even begin to diagnose the problem?
