### ISSUE TITLE
Should podcli exit with errorlevel for unknown command?

### ISSUE THREAD

**Issue by Jaykul** [stefanprodan/podinfo#401]
I discovered this morning that if we make a mistake in the command-line for podcli, the healthchecks always "pass" without checking anything. For instance, if someone tries this:

```yaml
        readinessProbe:
          exec:
            command:
            - podcli
            - check
            - https
            - localhost:9898/readyz
          initialDelaySeconds: 5
          timeoutSeconds: 5
```

It outputs the help, but doesn't produce a non-zero exit code, so the health check "passes"

Obviously, what they meant was this:

```yaml
        readinessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - https://localhost:9898/readyz
          initialDelaySeconds: 5
          timeoutSeconds: 5
```
