### ISSUE TITLE
servicemonitor required with prometheus-operator

### ISSUE THREAD

**Issue by faizan82** [stefanprodan/podinfo#51]
Running podinfo with flux-operator, Prometheus-operator fails to list podinfo as target. Looks like we need a [servicemonitor ](https://coreos.com/operators/prometheus/docs/latest/user-guides/getting-started.html). Not sure what needs to be added here as this does not work for me 

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo
  labels:
    app: podinfo
spec:
  endpoints:
    - port: "9797"
  selector:
    matchLabels:
      app: podinfo
```

**Comment by stefanprodan** [comment]
The metrics port is not expose on the service, you need a PodMonitor.

**Comment by stefanprodan** [comment]
You can also use the main port as the metrics endpoint is also exposed there:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo
  labels:
    app: podinfo
spec:
  endpoints:
    - port: "9898"
  selector:
    matchLabels:
      app: podinfo
```

**Comment by faizan82** [comment]
Thanks! This was not clear from the documentation. Also using [SO](https://stackoverflow.com/questions/52991038/how-to-create-a-servicemonitor-for-prometheus-operator) got to know that we need to have a service specifically created for podinfo which will be referenced by serviceMonitor. Also, the serviceMonitor will need to specify label specified in prometheus which looks something like this:
```yaml
    serviceMonitorSelector:
      matchLabels:
        release: demo-prom-new
```
